# Ollama Parameters Contract
# conf/base/parameters.yml の ollama セクション定義
#
# Feature: 051-ollama-params-config
# Date: 2026-02-15

# ============================================================
# Ollama Parameters (NEW: per-function configuration)
# ============================================================

ollama:
  # Default settings applied to all functions
  defaults:
    model: "gemma3:12b"              # Model name (required)
    base_url: "http://localhost:11434"  # Ollama server URL (required)
    timeout: 120                     # Request timeout in seconds (1-600)
    temperature: 0.2                 # Sampling temperature (0.0-2.0)
    num_predict: -1                  # Max output tokens (-1 = unlimited, or >= 1)

  # Per-function overrides (all fields optional)
  functions:
    # Knowledge extraction: long output (detailed markdown)
    extract_knowledge:
      num_predict: 16384             # Sufficient for detailed summaries
      timeout: 300                   # Extended timeout for long content

    # Summary translation: medium output
    translate_summary:
      num_predict: 1024              # Enough for translated summary

    # Topic extraction: very short output (1-3 words)
    extract_topic:
      model: "llama3.2:3b"           # Lighter model for simple task
      num_predict: 64                # Short output (topic name only)
      timeout: 30                    # Fast timeout

# ============================================================
# Schema Validation Rules
# ============================================================
#
# 1. ollama.defaults: REQUIRED
#    - model: REQUIRED, non-empty string
#    - base_url: REQUIRED, valid URL format
#    - timeout: OPTIONAL (default: 120), range 1-600
#    - temperature: OPTIONAL (default: 0.2), range 0.0-2.0
#    - num_predict: OPTIONAL (default: -1), -1 or >= 1
#
# 2. ollama.functions: OPTIONAL
#    - Valid keys: extract_knowledge, translate_summary, extract_topic
#    - Unknown keys are ignored (warning logged)
#    - All fields within each function are optional (inherit from defaults)
#
# 3. Fallback Order:
#    a. ollama.functions.{function_name}.{param}
#    b. ollama.defaults.{param}
#    c. Hardcoded default value

# ============================================================
# Backward Compatibility (DEPRECATED - will be removed)
# ============================================================

# Legacy structure (still supported but deprecated):
#
# import:
#   ollama:
#     model: "gemma3:12b"
#     ...
#
# organize:
#   ollama:
#     model: "gemma3:12b"
#     ...
#
# Migration: Move import.ollama and organize.ollama to ollama.defaults
